import type { FeedItem } from "./types";

/**
 * Sample feed data for demonstration mode ONLY.
 * All records use generic organisation names and verification_status: "demo".
 * These records must never appear in live mode or claim to be verified.
 */
export const sampleFeed: FeedItem[] = [
  {
    id: 121,
    external_id: "dis-001",
    category: "disaster",
    title: "Demonstration Flood Safety Advisory",
    summary: "Demonstration alert: Heavy monsoon rainfall may cause rising water levels near river basins. This is a sample advisory for interface demonstration purposes.",
    source_name: "Demonstration Disaster Source",
    source_url: "https://example.org/alerts/dis-001",
    image_url: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=600&auto=format&fit=crop",
    published_at: "2026-01-15T10:30:00Z",
    collected_at: "2026-01-15T10:35:00Z",
    last_checked_at: "2026-01-15T12:15:00Z",
    updated_at: "2026-01-15T12:15:00Z",
    expires_at: "2026-01-20T18:00:00Z",
    location: "Demonstration Region",
    tags: "flood;rain;emergency;shelter;evacuation",
    severity: "critical",
    verification_status: "demo",
    source_reliability: 0.5,
    data_mode: "demo",
  },
  {
    id: 101,
    external_id: "job-001",
    category: "job",
    title: "Demonstration Opportunity — Junior Data Analyst (Remote)",
    summary: "A sample remote analytics role for interface demonstration. Requires Python, SQL, and data cleaning skills.",
    source_name: "Demonstration Employer",
    source_url: "https://example.org/jobs/job-001",
    image_url: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop",
    published_at: "2026-01-15T07:30:00Z",
    collected_at: "2026-01-15T08:00:00Z",
    last_checked_at: "2026-01-15T11:30:00Z",
    updated_at: "2026-01-15T11:30:00Z",
    expires_at: "2026-03-10T23:59:00Z",
    location: "Demonstration Location; Remote",
    tags: "data science;python;sql;analytics",
    severity: "medium",
    verification_status: "demo",
    source_reliability: 0.5,
    employment_type: "Full-time",
    salary_text: "Sample compensation range",
    eligibility: "BS / MS in Computer Science or related field (demonstration listing)",
    data_mode: "demo",
  },
  {
    id: 104,
    external_id: "sch-001",
    category: "scholarship",
    title: "Demonstration Scholarship — Data Science Master's Programme",
    summary: "A sample fully funded scholarship for interface demonstration. Covers tuition and monthly stipend.",
    source_name: "Demonstration Education Foundation",
    source_url: "https://example.org/scholarships/sch-001",
    image_url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop",
    published_at: "2026-01-10T08:00:00Z",
    collected_at: "2026-01-10T08:30:00Z",
    last_checked_at: "2026-01-15T12:00:00Z",
    updated_at: "2026-01-15T12:00:00Z",
    expires_at: "2026-04-30T23:59:00Z",
    location: "International (Demonstration)",
    tags: "data science;masters;scholarship;international",
    severity: "high",
    verification_status: "demo",
    source_reliability: 0.5,
    funding_type: "Demonstration: Fully Funded",
    study_level: "Master's Degree",
    eligibility: "Open to international candidates (demonstration listing)",
    data_mode: "demo",
  },
  {
    id: 122,
    external_id: "weather-001",
    category: "weather",
    title: "Demonstration Heat Safety Advisory",
    summary: "Demonstration alert: High daytime temperatures expected. Reduce outdoor exposure during peak hours. This is a sample advisory.",
    source_name: "Demonstration Weather Source",
    source_url: "https://example.org/weather/heat",
    image_url: "https://images.unsplash.com/photo-1504370805625-d32c54b16100?w=600&auto=format&fit=crop",
    published_at: "2026-01-15T05:00:00Z",
    collected_at: "2026-01-15T05:05:00Z",
    last_checked_at: "2026-01-15T12:00:00Z",
    updated_at: "2026-01-15T12:00:00Z",
    expires_at: "2026-01-20T18:00:00Z",
    location: "Demonstration City",
    tags: "heat;health;hydration;advisory",
    severity: "high",
    verification_status: "demo",
    source_reliability: 0.5,
    data_mode: "demo",
  },
  {
    id: 102,
    external_id: "job-002",
    category: "job",
    title: "Demonstration Opportunity — Machine Learning Intern",
    summary: "A sample internship for interface demonstration. Focus on model evaluation and NLP.",
    source_name: "Demonstration Research Organisation",
    source_url: "https://example.org/jobs/job-002",
    published_at: "2026-01-12T12:00:00Z",
    collected_at: "2026-01-12T12:30:00Z",
    last_checked_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-01-15T10:00:00Z",
    expires_at: "2026-03-25T23:59:00Z",
    location: "Demonstration Location; Remote",
    tags: "machine learning;python;pandas;internship",
    severity: "medium",
    verification_status: "demo",
    source_reliability: 0.5,
    employment_type: "Internship (6 Months)",
    salary_text: "Sample stipend",
    data_mode: "demo",
  },
  {
    id: 105,
    external_id: "sch-002",
    category: "scholarship",
    title: "Demonstration Fellowship — Inclusive Technology",
    summary: "A sample fellowship for interface demonstration. Supports research in accessibility technology.",
    source_name: "Demonstration Assistive Tech Organisation",
    source_url: "https://example.org/scholarships/sch-002",
    published_at: "2026-01-08T10:00:00Z",
    collected_at: "2026-01-08T11:00:00Z",
    last_checked_at: "2026-01-15T12:10:00Z",
    updated_at: "2026-01-15T12:10:00Z",
    expires_at: "2026-05-15T23:59:00Z",
    location: "International (Demonstration)",
    tags: "accessibility;research;fellowship;ai",
    severity: "medium",
    verification_status: "demo",
    source_reliability: 0.5,
    funding_type: "Demonstration: Research Grant",
    data_mode: "demo",
  },
  {
    id: 131,
    external_id: "service-001",
    category: "service",
    title: "Demonstration Community Centre — Emergency Shelter",
    summary: "Demonstration listing: A sample 24-hour facility providing emergency shelter. For interface demonstration only.",
    source_name: "Demonstration Community Network",
    source_url: "https://example.org/services/service-001",
    published_at: "2026-01-01T00:00:00Z",
    collected_at: "2026-01-01T00:10:00Z",
    last_checked_at: "2026-01-15T06:00:00Z",
    updated_at: "2026-01-15T06:00:00Z",
    expires_at: null,
    location: "Demonstration District",
    tags: "shelter;accessible;community;demonstration",
    severity: "medium",
    verification_status: "demo",
    source_reliability: 0.5,
    data_mode: "demo",
  },
  {
    id: 141,
    external_id: "safety-001",
    category: "safety",
    title: "Demonstration Safety Notice — Advance Fee Scam",
    summary: "Demonstration alert: Sample scam warning for interface testing. Never pay fees through personal transfers.",
    source_name: "Demonstration Safety Advisory",
    source_url: "https://example.org/safety/safety-001",
    published_at: "2026-01-13T15:00:00Z",
    collected_at: "2026-01-13T15:05:00Z",
    last_checked_at: "2026-01-15T09:30:00Z",
    updated_at: "2026-01-15T09:30:00Z",
    expires_at: null,
    location: "Demonstration Region",
    tags: "scam;safety;advance fee;demonstration",
    severity: "high",
    verification_status: "demo",
    source_reliability: 0.5,
    data_mode: "demo",
  },
  {
    id: 151,
    external_id: "learning-001",
    category: "learning",
    title: "Demonstration Learning Path — SQL & Database Fundamentals",
    summary: "Demonstration listing: A sample learning curriculum for SQL and database concepts. For interface demonstration only.",
    source_name: "Demonstration Learning Platform",
    source_url: "https://example.org/learning/sql",
    published_at: "2026-01-05T09:00:00Z",
    collected_at: "2026-01-05T09:05:00Z",
    last_checked_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-01-15T08:00:00Z",
    expires_at: null,
    location: "Online (Demonstration)",
    tags: "sql;database;learning;demonstration",
    severity: "low",
    verification_status: "demo",
    source_reliability: 0.5,
    data_mode: "demo",
  },
];
